# Generated by Django 5.0.3 on 2024-06-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='full_title',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='subsubcategory',
            name='full_title',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
