# Generated by Django 5.0.3 on 2024-06-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_subcategory_full_title_subsubcategory_full_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='query_title',
            field=models.CharField(default=1, max_length=1200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='query_title',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='subsubcategory',
            name='query_title',
            field=models.CharField(default=1, max_length=1200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='title',
            field=models.CharField(max_length=1200),
        ),
    ]
