# Generated by Django 5.0.3 on 2024-06-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_query_title_subcategory_query_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='query_title',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='query_title',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
