# Generated by Django 5.0.3 on 2024-06-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_base_price_remove_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_signature',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OurTopDeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('banner_url', models.CharField(max_length=1500)),
                ('products', models.ManyToManyField(related_name='top_deals', to='product.product')),
            ],
        ),
    ]
