# Generated by Django 5.0.3 on 2024-06-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_is_signature_ourtopdeals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourtopdeals',
            options={'verbose_name_plural': 'Our Top Deals'},
        ),
    ]
