# Generated by Django 5.0.3 on 2024-06-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_ourtopdeals_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeherunSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('banner_url', models.CharField(max_length=1500)),
                ('products', models.ManyToManyField(related_name='signature', to='product.product')),
            ],
            options={
                'verbose_name_plural': "Meherun's Signature",
            },
        ),
    ]
