# Generated by Django 5.0.3 on 2024-06-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_meherunsignature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='image',
        ),
        migrations.AddField(
            model_name='productimages',
            name='image_url',
            field=models.CharField(default=None, max_length=1200),
        ),
    ]
