# Generated by Django 5.0.3 on 2024-06-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_productimages_image_productimages_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariation',
            old_name='size',
            new_name='dimension',
        ),
        migrations.RenameField(
            model_name='productvariation',
            old_name='selling_price',
            new_name='new_price',
        ),
    ]
