# Generated by Django 5.0.3 on 2024-06-11 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_size_productvariation_dimension_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OurTopDeals',
            new_name='OurBestDeals',
        ),
    ]
