# Generated by Django 5.0.3 on 2024-06-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_ourtopdeals_ourbestdeals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourbestdeals',
            options={'verbose_name_plural': 'Our Best Deals'},
        ),
    ]
