# Generated by Django 5.0.3 on 2024-06-13 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_product_is_new_remove_product_is_top_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='new_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
    ]
