# Generated by Django 5.0.3 on 2024-06-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_product_new_price_remove_product_old_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='is_top',
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
