# Generated by Django 5.0.3 on 2024-06-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_productvariation_is_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
