# Generated by Django 5.0.3 on 2024-06-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_new_price_product_old_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_deal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_signature',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='is_deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='is_signature',
            field=models.BooleanField(default=False),
        ),
    ]
