# Generated by Django 5.0.3 on 2024-06-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_meherunsignature_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='full_title',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
