# Generated by Django 5.0.3 on 2024-06-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_productvariation_full_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('products', models.ManyToManyField(related_name='banner_products', to='product.productvariation')),
            ],
            options={
                'verbose_name_plural': 'Banner Related Products',
            },
        ),
    ]
