# Generated by Django 5.0.3 on 2024-06-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_bannerproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='is_banner_product',
            field=models.BooleanField(default=False),
        ),
    ]
