# Generated by Django 5.0.3 on 2024-06-20 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_alter_bannercarousel_options_and_more'),
        ('product', '0018_productvariation_is_banner_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerproducts',
            name='banner_obj',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='banner.bannercarousel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bannerproducts',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
