# Generated by Django 5.0.3 on 2024-06-22 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0007_carouselbanner'),
        ('product', '0019_bannerproducts_banner_obj_alter_bannerproducts_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerproducts',
            name='banner_obj',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='banner.carouselbanner'),
        ),
    ]
