# Generated by Django 5.0.3 on 2024-06-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_bannerproducts_banner_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerproducts',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meherunsignature',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ourbestdeals',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
