# Generated by Django 5.0.3 on 2024-07-03 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_bannerproducts_is_active_meherunsignature_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyBroughtTogether',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequently_brought_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequently_brought_product', to='product.product')),
                ('main_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='product.product')),
            ],
            options={
                'verbose_name_plural': 'Frequently Brought Together',
            },
        ),
    ]
