# Generated by Django 5.0.3 on 2024-07-03 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_frequentlybroughttogether'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_for_recommended_product', to='product.product')),
                ('recommended', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_product', to='product.product')),
            ],
        ),
    ]
