# Generated by Django 5.0.3 on 2024-07-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_recommendedproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedproduct',
            name='recommended',
        ),
        migrations.AddField(
            model_name='recommendedproduct',
            name='recommended_product_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='frequentlybroughttogether',
            name='frequently_brought_product',
            field=models.IntegerField(),
        ),
    ]
