# Generated by Django 5.0.3 on 2024-07-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_remove_recommendedproduct_recommended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentlybroughttogether',
            name='total_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
