# Generated by Django 5.0.3 on 2024-07-06 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_frequentlybroughttogether_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequentlybroughttogether',
            old_name='frequently_brought_product',
            new_name='frequently_brought_product_id',
        ),
    ]
