# Generated by Django 5.0.3 on 2024-07-06 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_rename_frequently_brought_product_frequentlybroughttogether_frequently_brought_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequentlybroughttogether',
            name='main_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_fbt_product', to='product.product'),
        ),
    ]
