# Generated by Django 5.0.3 on 2024-07-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_alter_frequentlybroughttogether_main_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouMayAlsoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
            ],
        ),
    ]
