# Generated by Django 5.0.3 on 2024-07-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_youmayalsolike'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
