# Generated by Django 5.0.3 on 2024-07-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_productvariation_is_new_productvariation_is_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='stock_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
