# Generated by Django 5.0.3 on 2024-07-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_productvariation_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='full_title',
            field=models.CharField(blank=True, db_index=True, max_length=1200, null=True),
        ),
    ]
