# Generated by Django 5.0.3 on 2024-07-27 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_brand_banner_url_brand_is_active_and_more'),
        ('product', '0032_alter_productvariation_full_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brand_products', to='brand.brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariation',
            name='brand_feature',
            field=models.BooleanField(default=False),
        ),
    ]
