# Generated by Django 5.0.3 on 2024-07-27 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_brand_banner_url_brand_is_active_and_more'),
        ('product', '0033_productvariation_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_products', to='brand.brand'),
        ),
    ]
