# Generated by Django 5.0.3 on 2024-08-07 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_alter_productvariation_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequentlybroughttogether',
            name='total_price',
        ),
    ]
