# Generated by Django 5.0.3 on 2024-08-17 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_remove_frequentlybroughttogether_total_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrequentlyBroughtTogether',
        ),
    ]
