# Generated by Django 5.0.3 on 2024-08-17 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_delete_frequentlybroughttogether'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyBroughtTogether',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequently_brought_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fbt_product', to='product.productvariation')),
                ('main_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fbt_main', to='product.product')),
            ],
            options={
                'verbose_name_plural': 'Frequently Brought Together',
            },
        ),
    ]
