# Generated by Django 5.0.3 on 2024-08-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_frequentlybroughttogether'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
