# Generated by Django 5.0.3 on 2024-08-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='sku',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
