# Generated by Django 5.0.3 on 2024-08-31 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_brand_banner_url_brand_is_active_and_more'),
        ('product', '0039_remove_product_sku_productvariation_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_products', to='brand.brand'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_product_variations', to='brand.brand'),
        ),
    ]
