# Generated by Django 5.0.3 on 2024-09-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_product_brand_alter_productvariation_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='last_selling_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
