# Generated by Django 5.0.3 on 2024-09-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_alter_productvariation_last_selling_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='last_selling_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
