# Generated by Django 5.0.3 on 2024-09-04 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_alter_productvariation_last_selling_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariation',
            old_name='last_selling_date',
            new_name='last_bought',
        ),
    ]
