# Generated by Django 5.0.3 on 2024-09-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_rename_last_selling_date_productvariation_last_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
