# Generated by Django 5.0.3 on 2024-09-12 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_alter_bannerproducts_banner_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youmayalsolike',
            name='product_id',
        ),
        migrations.AddField(
            model_name='youmayalsolike',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='you_may_also_like_products', to='product.productvariation'),
        ),
    ]
