from django.urls import path
from . import views
from .views import OrderCreateAPIView,AnonymousOrderCreateAPIView
urlpatterns = [
    path('v1/checkout/',OrderCreateAPIView.as_view(), name="checkout"),
    path('v1/anonymous/checkout/',AnonymousOrderCreateAPIView.as_view(), name="anonymous_checkout"),
    path('v1/get-orders/',views.get_orders, name="get_orders"),
    path('v1/get-order-items/',views.get_order_items, name="get_order_items"),
    path('v1/order-complete/',views.order_complete, name="order_complete"),
    path('v1/get-all-orders/',views.get_all_orders, name="get_all_orders"),
    path('v1/get-order-details/',views.get_order_details, name="get_order_details"),
    path('v1/delete-order/',views.delete_order, name="delete_order"),
    path('v1/change-order-status/',views.change_order_status, name="change_order_status"),
    path('v1/get-all-abandon-carts/',views.get_all_abandon_carts, name="get_all_abandon_carts"),
    path('v1/get-abandon-cart-details/',views.get_abandon_cart_details, name="get_abandon_cart_details"),
    path('v1/delete-abandon-cart/',views.delete_abandon_cart, name="delete_abandon_cart"),
    path('v1/coupon-code-verify/',views.coupon_code_verify, name="coupon_code_verify"),
    path('v1/save-coupon-code/',views.save_coupon_code, name="save_coupon_code"),
    path('v1/get-coupons/',views.get_coupons, name="get_coupons"),
    path('v1/change-coupon-active-status/',views.change_coupon_active_status, name="change_coupon_active_status"),
    path('v1/update-coupon/',views.update_coupon, name="update_coupon"),
    path('v1/delete-coupon/',views.delete_coupon, name="delete_coupon"),
    path('v1/save-store-pickup-location/',views.save_store_pickup_location, name="save_store_pickup_location"),
    path('v1/update-store-pickup-location/',views.update_store_pickup_location, name="update_store_pickup_location"),
    path('v1/delete-store-pickup-location/',views.delete_store_pickup_location, name="delete_store_pickup_location"),
    path('v1/get-store-pickup-locations/',views.get_store_pickup_locations, name="get_store_pickup_locations"),
    path('v1/get-product-subscriptions/',views.get_product_subscriptions, name="get_product_subscriptions"),
    path('v1/complete-product-subscription/',views.complete_product_subscription, name="complete_product_subscription"),
    path('v1/update-subscription-due-date/',views.update_subscription_due_date, name="update_subscription_due_date"),
    path('v1/delete-selected-abandoned-cart/',views.delete_selected_abandoned_cart, name="delete_selected_abandoned_cart"),
    path('v1/delete-multiple-store-pickup-location/',views.delete_multiple_store_pickup_location, name="delete_multiple_store_pickup_location"),
    path('v1/delete-multiple-coupon/',views.delete_multiple_coupon, name="delete_multiple_coupon"),
    path('v1/delete-multiple-order/',views.delete_multiple_order, name="delete_multiple_order"),
    path('v1/get-product-subscription-verification/',views.get_product_subscription_verification, name="get_product_subscription_verification"),
    path('v1/get-user-product-subscription/',views.get_user_product_subscription, name="get_user_product_subscription"),
]