# Generated by Django 5.0.3 on 2024-07-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_product_cart_product_variation_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='price',
            new_name='new_price',
        ),
        migrations.AddField(
            model_name='cart',
            name='old_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
