# Generated by Django 5.0.3 on 2024-07-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='dimension',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='title',
            field=models.CharField(default=1, max_length=1500),
            preserve_default=False,
        ),
    ]
