# Generated by Django 5.0.3 on 2024-07-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product_variation',
            new_name='product',
        ),
    ]
