# Generated by Django 5.0.3 on 2024-08-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outside_dhaka', models.FloatField()),
                ('inside_dhaka', models.FloatField()),
            ],
        ),
    ]
