# Generated by Django 5.0.3 on 2024-08-18 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_puchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puchase',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Puchase',
        ),
    ]
