# Generated by Django 5.0.3 on 2024-08-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0003_remove_chatmessage_sender_chatmessage_sender_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='sender_id',
            field=models.IntegerField(),
        ),
    ]
