# Generated by Django 5.0.3 on 2024-08-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0004_alter_chatroom_sender_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchatmessages',
            name='user',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='color_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.DeleteModel(
            name='AdminReply',
        ),
        migrations.DeleteModel(
            name='UserChatMessages',
        ),
    ]
