# Generated by Django 5.0.3 on 2024-08-14 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0005_remove_userchatmessages_user_chatroom_color_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_read',
        ),
    ]
