# Generated by Django 5.0.3 on 2024-08-14 07:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0006_remove_chatmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='update_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
