# Generated by Django 5.0.3 on 2024-08-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0007_chatroom_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
