# Generated by Django 5.0.3 on 2024-07-08 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0029_youmayalsolike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=14, verbose_name='Contact Number')),
                ('country', models.CharField(max_length=100, verbose_name='Country Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('post_code', models.CharField(max_length=50, verbose_name='Post Code')),
                ('total_amount', models.FloatField(verbose_name='Total Payment')),
                ('payment_mode', models.CharField(max_length=250)),
                ('tracking_no', models.CharField(max_length=250, verbose_name='Tracking ID')),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Pending', max_length=250, verbose_name='Order Status')),
                ('payment_status', models.BooleanField(default=False, verbose_name='Payment Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creating Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updating Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_product', to='product.productvariation')),
            ],
        ),
    ]
