# Generated by Django 5.0.3 on 2024-07-10 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_first_name_remove_order_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=14, verbose_name='Contact Number')),
                ('country', models.CharField(max_length=100, verbose_name='Country Name')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('address', models.TextField(verbose_name='Address')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_shipping_details', to='order.order')),
            ],
        ),
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
