# Generated by Django 5.0.3 on 2024-07-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_couponcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
