# Generated by Django 5.0.3 on 2024-07-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderitems_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingdetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shippingdetails',
            name='name',
        ),
        migrations.RemoveField(
            model_name='shippingdetails',
            name='phone',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Received', 'Received'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Pending', max_length=250, verbose_name='Order Status'),
        ),
    ]
