# Generated by Django 5.0.3 on 2024-07-13 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_shippingdetails_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingdetails',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_shipping_details', to='order.order'),
        ),
    ]
