# Generated by Django 5.0.3 on 2024-07-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_shippingdetails_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orde_abandoned',
            field=models.BooleanField(default=False, verbose_name='Cart Abandonment'),
        ),
    ]
