# Generated by Django 5.0.3 on 2024-07-30 05:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_orde_abandoned_abandoncart'),
    ]

    operations = [
        migrations.AddField(
            model_name='abandoncart',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creating Date'),
        ),
        migrations.AddField(
            model_name='abandoncart',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Update Date'),
        ),
    ]
