# Generated by Django 5.0.3 on 2024-07-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_abandoncart_created_at_abandoncart_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abandoncart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creating Date'),
        ),
        migrations.AlterField(
            model_name='abandoncart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Date'),
        ),
    ]
