# Generated by Django 5.0.3 on 2024-07-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_rename_orde_abandoned_order_order_abandoned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
