# Generated by Django 5.0.3 on 2024-07-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_couponcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
