# Generated by Django 5.0.3 on 2024-08-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_couponcode_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_percentage',
            field=models.FloatField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitems',
            name='dimension',
            field=models.CharField(default=200, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='shipping_cost',
            field=models.FloatField(default=30),
            preserve_default=False,
        ),
    ]
