# Generated by Django 5.0.3 on 2024-08-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_order_discount_percentage_orderitems_dimension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sub_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
