# Generated by Django 5.0.3 on 2024-08-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_order_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Payment'),
        ),
    ]
