# Generated by Django 5.0.3 on 2024-08-03 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_order_shipping_cost_alter_order_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingdetails',
            name='shipping_cost',
        ),
    ]
