# Generated by Django 5.0.3 on 2024-08-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_remove_shippingdetails_shipping_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePickupLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
            ],
        ),
    ]
