# Generated by Django 5.0.3 on 2024-08-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_storepickuplocations'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepickuplocations',
            name='branch_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
