# Generated by Django 5.0.3 on 2024-08-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_storepickuplocations_branch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subscription',
            field=models.BooleanField(default=False, verbose_name='Subscribed'),
        ),
        migrations.AddField(
            model_name='order',
            name='subscription_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
