# Generated by Django 5.0.3 on 2024-08-05 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_order_subscription_order_subscription_type'),
        ('product', '0034_alter_productvariation_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_product_order', to='order.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribed_product', to='product.productvariation')),
            ],
        ),
    ]
