# Generated by Django 5.0.3 on 2024-08-06 08:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_subscribedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribedproduct',
            name='last_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscribedproduct',
            name='next_due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
