# Generated by Django 5.0.3 on 2024-08-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_subscribedproduct_last_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='subscription_type',
        ),
        migrations.AddField(
            model_name='subscribedproduct',
            name='subscription_type',
            field=models.CharField(choices=[('W', 'Weekly'), ('M', 'Monthly'), ('2M', 'Every 2 Months'), ('3M', 'Every 3 Months')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
