# Generated by Django 5.0.3 on 2024-08-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_remove_order_subscription_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedproduct',
            name='subscription_type',
            field=models.CharField(choices=[('W', 'Weekly'), ('M', 'Monthly'), ('2M', 'Every 2 Months'), ('3M', 'Every 3 Months')], default='Weekly', max_length=2),
        ),
    ]
