# Generated by Django 5.0.3 on 2024-08-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_alter_subscribedproduct_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subscription_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='SubscribedProduct',
        ),
    ]
