# Generated by Django 5.0.3 on 2024-08-10 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_order_subscription_type_delete_subscribedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='next_due_date',
            field=models.DateField(default=datetime.date(2024, 8, 10)),
        ),
    ]
