# Generated by Django 5.0.3 on 2024-08-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_order_next_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='next_due_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
