# Generated by Django 5.0.3 on 2024-06-20 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannercarousel',
            options={'verbose_name_plural': 'Carousel Banner'},
        ),
        migrations.AlterModelOptions(
            name='titlebanner',
            options={'verbose_name_plural': 'Title Banners'},
        ),
    ]
