# Generated by Django 5.0.3 on 2024-06-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_alter_bannercarousel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannercarousel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
