# Generated by Django 5.0.3 on 2024-06-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_bannercarousel_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleBannerOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('banner_url', models.CharField(max_length=1500)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Title Banners',
            },
        ),
        migrations.CreateModel(
            name='TitleBannerTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('banner_url', models.CharField(max_length=1500)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Title Banners',
            },
        ),
        migrations.DeleteModel(
            name='TitleBanner',
        ),
    ]
