# Generated by Django 5.0.3 on 2024-06-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_titlebannerone_titlebannertwo_delete_titlebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannercarousel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
