# Generated by Django 5.0.3 on 2024-06-22 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0005_bannercarousel_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannercarousel',
            name='created_at',
        ),
    ]
