# Generated by Django 5.0.3 on 2024-06-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0007_carouselbanner'),
        ('product', '0020_alter_bannerproducts_banner_obj'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerCarousel',
        ),
    ]
