# Generated by Django 5.0.3 on 2024-06-22 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0008_delete_bannercarousel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TitleBannerOne',
        ),
        migrations.DeleteModel(
            name='TitleBannerTwo',
        ),
    ]
