# Generated by Django 5.0.3 on 2024-06-22 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0010_titlebannerone_titlebannertwo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titlebannerone',
            options={'verbose_name_plural': 'Title Banners One'},
        ),
        migrations.AlterModelOptions(
            name='titlebannertwo',
            options={'verbose_name_plural': 'Title Banners Two'},
        ),
    ]
