# Generated by Django 5.0.3 on 2024-09-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0011_alter_titlebannerone_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('banner_url', models.CharField(max_length=1500)),
                ('is_active', models.BooleanField(default=False)),
                ('banner_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Banners',
            },
        ),
    ]
