# Generated by Django 5.0.3 on 2024-09-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0012_allbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='allbanner',
            name='is_navigate',
            field=models.BooleanField(default=False),
        ),
    ]
