# Generated by Django 5.0.3 on 2024-07-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailforoutofstockproducts',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent')], default='Pending', max_length=250, verbose_name='Status'),
        ),
    ]
