# Generated by Django 5.0.3 on 2024-09-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='replied',
            field=models.BooleanField(default=False),
        ),
    ]
