# Generated by Django 5.0.3 on 2024-09-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_contactus_replied'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='replied_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
