# Generated by Django 5.0.3 on 2024-09-14 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_contactus_replied_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='replied',
            new_name='is_replied',
        ),
    ]
