# Generated by Django 5.0.3 on 2024-09-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_rename_replied_contactus_is_replied'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
