# Generated by Django 5.0.3 on 2024-07-14 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0029_youmayalsolike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('brand_logo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BrandProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField()),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='brand.brand')),
                ('product', models.ManyToManyField(related_name='brand_products', to='product.product')),
            ],
        ),
    ]
