# Generated by Django 5.0.3 on 2024-07-14 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandproducts',
            old_name='product',
            new_name='products',
        ),
    ]
