# Generated by Django 5.0.3 on 2024-07-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_rename_product_brandproducts_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='banner_url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='BrandProducts',
        ),
    ]
